name: MSDocs build verifier - tryfix
on:
  issue_comment:
    types: [created]

jobs:
  tryfix:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/tryfix')
    name: Try fix build
    runs-on: ubuntu-latest
    env:
      IS_TRY_FIX: true # differentiates /tryfix from the validation-only run.
      GITHUB_PR_NUMBER: ${{ github.event.issue.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 #@v2

    - name: Tryfix
      uses: Youssef1313/docs-actions/actions/docs-verifier@feature-autofix
