on:
  pull_request:
    types: [opened]

jobs:
  comment:
    if: github.event.issue.pull_request != '' && context.payload.sender.login != 'cxwtool'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test comment'
            })
